name: crm-dunning-service-production

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    image: postgres:16.4-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data:
