services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql:data
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  seq:
    image: datalust/seq:latest
    ports: ['${SEQ_SERVER_PORT}:80']
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=whatisthis

  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - '127.0.0.1:${AWS_PORT}:${AWS_PORT}' # LocalStack Gateway
  #     - '127.0.0.1:4510-4559:4510-4559' # external services port range
  #   environment:
  #     - DEBUG=${DEBUG:-0}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'

  mockoon:
    image: mockoon/cli:latest
    command: ['--data', 'data', '--port', '3000']
    ports: ['3000:3000']
    volumes:
      - ./mockoon/external-services.json:/data:readonly

volumes:
  postgres-data:
